name: Build, test, lint

on:
  - push
  - pull_request

permissions: read-all

jobs:
  task21:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task21

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4.14

      - name: Install dependencies
        run: |
          eval $(opam env)
          opam install . --deps-only --with-test

      - name: Install Dune
        run: |
          eval $(opam env)
          opam install dune

      - name: Build
        run: |
          eval $(opam env)
          dune build

      - name: Run tests
        run: |
          eval $(opam env)
          dune runtest

      - name: Execute task
        run: |
          eval $(opam env)
          dune exec task21