name: Build, test, lint

on:
  - push
  - pull_request

permissions: read-all

jobs:
  task10:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: 4.14.0

    - name: Install dependencies
      run: opam install . --deps-only --with-test
    
    - name: Run tests
      run: dune exec task10
  
  task21:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task21

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-version: 4.14.0

    - name: Install dependencies
      run: opam install . --deps-only --with-test
    
    - name: Run tests
      run: dune exec task21